### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by dfiorini** [AginSquash/open2fa#39]
Hi, how can I download this app for my Mac ?

**Comment by AginSquash** [comment]
Hi! Unfortunately, I don't have a developer account for signing apps. So the only option is to compile application from the source code ☹️

**Comment by AginSquash** [comment]
Here are the instructions for compile: https://github.com/AginSquash/open2fa#getting-started

**Comment by mintyleaf** [comment]
btw you can still put a built binary into the releases and let user codesign it by thyself providing similar instructions

see
https://github.com/inedible-dev/MusicBar/discussions/6

**Comment by AginSquash** [comment]
@mintyleaf 

Hi! Just rewrote the core of the app and posted it to the AppStore.
Haven't gotten around to making an announcement on github yet, but here's the link:

https://apps.apple.com/ru/app/open2fa/id6497407368
